// components/public-section/home/upcoming-events/constants.ts

import { UpcomingEventItem, UpcomingEventsTab } from './types';

export const UPCOMING_EVENTS_TABS: UpcomingEventsTab[] = [
  { key: 'all', label: 'ทั้งหมด', hint: 'All events' },
  { key: 'today', label: 'วันนี้', hint: 'Today' },
  { key: 'week', label: 'สัปดาห์นี้', hint: 'This week' },
  { key: 'workshop', label: 'เวิร์กช็อป', hint: 'Workshop focus' },
  { key: 'nearby', label: 'ใกล้ฉัน', hint: 'Nearby' },
];

export const UPCOMING_EVENT_ITEMS: Record<string, UpcomingEventItem[]> = {
  all: [
    {
      id: 'upcoming-pottery',
      category: 'Workshop',
      title: 'Intro to Pottery & Clay Sculpting',
      dateLabel: 'พุธ, 2 ก.พ.',
      timeLabel: '2:00 PM',
      location: 'Art Lab',
      accent: 'amber',
    },
    {
      id: 'upcoming-python',
      category: 'Career',
      title: 'Python Bootcamp for Interns',
      dateLabel: 'พฤหัส, 3 ก.พ.',
      timeLabel: '6:00 PM',
      location: 'Innovation Hub',
      accent: 'cyan',
    },
    {
      id: 'upcoming-ai',
      category: 'Academic',
      title: 'AI Basics: Build Your First Assistant',
      dateLabel: 'ศุกร์, 4 ก.พ.',
      timeLabel: '10:30 AM',
      location: 'Lecture Hall 2',
      accent: 'violet',
    },
    {
      id: 'upcoming-run',
      category: 'Sports',
      title: 'Sunset Campus Run 5K',
      dateLabel: 'เสาร์, 5 ก.พ.',
      timeLabel: '5:30 PM',
      location: 'Main Gate',
      accent: 'emerald',
    },
    {
      id: 'upcoming-volunteer',
      category: 'Volunteer',
      title: 'Community Garden Volunteer Day',
      dateLabel: 'อาทิตย์, 6 ก.พ.',
      timeLabel: '9:00 AM',
      location: 'North Garden',
      accent: 'rose',
    },
  ],
  today: [
    {
      id: 'today-main',
      category: 'Today',
      title: 'Design Sprint: Campus Wayfinding',
      dateLabel: 'วันนี้',
      timeLabel: '1:00 PM',
      location: 'Studio A',
      accent: 'violet',
    },
    {
      id: 'today-talk',
      category: 'Today',
      title: 'Lunch Talk: Product Design Careers',
      dateLabel: 'วันนี้',
      timeLabel: '12:15 PM',
      location: 'Co-working Space',
      accent: 'cyan',
    },
    {
      id: 'today-walk',
      category: 'Today',
      title: 'Wellness Walkaround',
      dateLabel: 'วันนี้',
      timeLabel: '4:30 PM',
      location: 'Library Plaza',
      accent: 'emerald',
    },
    {
      id: 'today-photo',
      category: 'Today',
      title: 'Photo Walk: Light & Shadows',
      dateLabel: 'วันนี้',
      timeLabel: '5:00 PM',
      location: 'East Wing',
      accent: 'amber',
    },
    {
      id: 'today-music',
      category: 'Today',
      title: 'Acoustic Jam Session',
      dateLabel: 'วันนี้',
      timeLabel: '6:30 PM',
      location: 'Open Courtyard',
      accent: 'rose',
    },
  ],
  week: [
    {
      id: 'week-1',
      category: 'This Week',
      title: 'Creative Portfolio Review',
      dateLabel: 'จันทร์',
      timeLabel: '3:00 PM',
      location: 'Room 204',
      accent: 'violet',
    },
    {
      id: 'week-2',
      category: 'This Week',
      title: 'Startup Career Panel',
      dateLabel: 'อังคาร',
      timeLabel: '5:00 PM',
      location: 'Auditorium',
      accent: 'cyan',
    },
    {
      id: 'week-3',
      category: 'This Week',
      title: 'Weekend Robotics Demo',
      dateLabel: 'พฤหัส',
      timeLabel: '1:30 PM',
      location: 'Tech Lab',
      accent: 'amber',
    },
    {
      id: 'week-4',
      category: 'This Week',
      title: 'Evening Networking Mixer',
      dateLabel: 'ศุกร์',
      timeLabel: '7:00 PM',
      location: 'Sky Lounge',
      accent: 'emerald',
    },
    {
      id: 'week-5',
      category: 'This Week',
      title: 'Open Class: Motion Graphics',
      dateLabel: 'เสาร์',
      timeLabel: '10:00 AM',
      location: 'Media Lab',
      accent: 'rose',
    },
  ],
  workshop: [
    {
      id: 'workshop-1',
      category: 'Workshop',
      title: 'Intro to Pottery & Clay Sculpting',
      dateLabel: 'พุธ, 2 ก.พ.',
      timeLabel: '2:00 PM',
      location: 'Art Lab',
      accent: 'amber',
    },
    {
      id: 'workshop-2',
      category: 'Workshop',
      title: 'Design Systems for Beginners',
      dateLabel: 'พฤหัส, 3 ก.พ.',
      timeLabel: '4:00 PM',
      location: 'UI Studio',
      accent: 'violet',
    },
    {
      id: 'workshop-3',
      category: 'Workshop',
      title: 'Photography Light Setup',
      dateLabel: 'ศุกร์, 4 ก.พ.',
      timeLabel: '1:00 PM',
      location: 'Photo Room',
      accent: 'cyan',
    },
    {
      id: 'workshop-4',
      category: 'Workshop',
      title: 'Public Speaking Clinic',
      dateLabel: 'เสาร์, 5 ก.พ.',
      timeLabel: '11:00 AM',
      location: 'Seminar Hall',
      accent: 'rose',
    },
    {
      id: 'workshop-5',
      category: 'Workshop',
      title: 'No-Code App Prototype Lab',
      dateLabel: 'อาทิตย์, 6 ก.พ.',
      timeLabel: '9:30 AM',
      location: 'Innovation Hub',
      accent: 'emerald',
    },
  ],
  nearby: [
    {
      id: 'nearby-1',
      category: 'Nearby',
      title: 'Campus Food Fair',
      dateLabel: 'วันนี้',
      timeLabel: '5:00 PM',
      location: 'Central Lawn',
      accent: 'rose',
    },
    {
      id: 'nearby-2',
      category: 'Nearby',
      title: 'Open Mic at the Library',
      dateLabel: 'พรุ่งนี้',
      timeLabel: '6:30 PM',
      location: 'North Library',
      accent: 'violet',
    },
    {
      id: 'nearby-3',
      category: 'Nearby',
      title: 'Street Art Showcase',
      dateLabel: 'เสาร์',
      timeLabel: '4:00 PM',
      location: 'Art Alley',
      accent: 'amber',
    },
    {
      id: 'nearby-4',
      category: 'Nearby',
      title: 'Night Market After School',
      dateLabel: 'ศุกร์',
      timeLabel: '7:30 PM',
      location: 'West Gate',
      accent: 'cyan',
    },
    {
      id: 'nearby-5',
      category: 'Nearby',
      title: 'Morning Yoga at the Park',
      dateLabel: 'อาทิตย์',
      timeLabel: '7:00 AM',
      location: 'City Park',
      accent: 'emerald',
    },
  ],
};
